name: CI/CD

on:
    push:
        branches:
            - main

jobs:
    deploy_lambda:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - name: Configure AWS credentials 
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-south-1
            - name: Install dependencies
              env:
                 CI: true
              run: |
                  npm ci
            - name: deploy_lambda
              run: |
                  npx ncc build index.js -o dist
                  7z a deploy.zip ./dist/*
                  aws lambda update-function-code --function-name=upc-inc-lambda --zip-file=fileb://deploy.zip
                         